language: python
cache: pip
dist: bionic
matrix:
  fast_finish: true
  include:
  - python: '3.5'
    env: DJANGO=2.2
install:
- pip install tox tox-travis
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_2a68b6131c57_key -iv $encrypted_2a68b6131c57_iv
  -in root_key.enc -out root_key -d
